name: CI - Build & Push Backend Image

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/finote-backend
  REGISTRY: ghcr.io
  OWNER: rakafde

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: npm run build

      - name: Read VERSION
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set short SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image tags
        run: |
          VERSION=$(cat VERSION)
          SHORT_SHA=${GITHUB_SHA::7}

          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
            echo "${IMAGE_NAME}:latest" >> $GITHUB_ENV
            echo "${IMAGE_NAME}:${VERSION}" >> $GITHUB_ENV
            echo "${IMAGE_NAME}:${VERSION}-${SHORT_SHA}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
            echo "${IMAGE_NAME}:dev" >> $GITHUB_ENV
            echo "${IMAGE_NAME}:${VERSION}-dev-${SHORT_SHA}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_TAGS }}


